export const PLAYLISTS_COLLECTION = "PLAYLISTS_COLLECTION"
export const PODCASTS_COLLECTION = "PODCASTS_COLLECTION"
export const ARTISTS_COLLECTION = "ARTISTS_COLLECTION"
export const ALBUMS_COLLECTION = "ALBUMS_COLLECTION"